name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: Akki-8989/Infrastructure/.github/workflows/deploy-be-ecom-users.yml@main
    with:
      repo_name: be-ecom-users
      infra_repo: Infrastructure
    secrets: inherit
